CREATE TABLE COMPANY(
	ID VARCHAR2(100) PRIMARY KEY,
	NAME VARCHAR2(100),
	ADDR VARCHAR2(100),
	TEL VARCHAR2(100)
)

INSERT INTO COMPANY VALUES ('c100', 'GOOD', 'SEOUL', '011')

INSERT INTO COMPANY VALUES ('c200', 'JOA', 'BUSAN', '012')

INSERT INTO COMPANY VALUES ('c300', 'MARIA', 'ULSAN', '013')

INSERT INTO COMPANY VALUES ('c400', 'MY', 'KWANGJU', '014')

SELECT * FROM COMPANY

--------------------------------------------------

--inner join

SELECT * FROM PRODUCT p, COMPANY c 
WHERE (p.COMPANY = c.ID)

--LEFT/RIGHT OUTER JOIN

SELECT * FROM PRODUCT p 
LEFT OUTER JOIN COMPANY c 
ON (p.COMPANY = c.ID)

SELECT * FROM PRODUCT p 
right OUTER JOIN COMPANY c 
ON (p.COMPANY = c.ID)







