SELECT  CONCAT(CONCAT(EMPNO, ':'), ENAME) AS CONCAT_RESULT FROM EMP 

SELECT EMPNO || ':' || ENAME AS CONCAT_RESULT FROM EMP 


SELECT LENGTH(TRIM(ENAME)) FROM EMP 

SELECT TRIM(BOTH 'A' FROM ENAME) FROM EMP -- 양쪽끝에 A 제거

SELECT TRIM(LEADING 'A' FROM ENAME) FROM EMP -- 앞쪽에 A 제거

SELECT TRIM(TRAILING 'A' FROM ENAME) FROM EMP -- 뒤쪽에 A 제거

SELECT REPLACE(ENAME, ' ', '') FROM EMP

SELECT * FROM EMP

UPDATE EMP SET COMM = 0
WHERE COMM IS NULL

SELECT * FROM EMP

SELECT SAL + COMM AS TOTAL FROM EMP


