CREATE TABLE "HR"."BOARD3" 
   (	"BOARDNO" NUMBER(38,0), 
	"TITLE" VARCHAR2(100), 
	"CONTENTS" VARCHAR2(100), 
	"WRITER" VARCHAR2(100), 
	"DATEWRITE" DATE, 
	"RECOMMEND" NUMBER(38,0), 
	"VIEWCOUNT" NUMBER(38,0)
   ) 
   
   
   ALTER TABLE BOARD3 MODIFY WRITER VARCHAR2(200)
   
   ALTER TABLE BOARD3 DROP COLUMN VIEWCOUNT
   
   ALTER TABLE BOARD3 ADD TEST VARCHAR2(100)