
CREATE TABLE "HR"."NOTICE" 
   (	"BOARDNO" NUMBER(38,0), 
	"TITLE" VARCHAR2(100), 
	"CONTENTS" VARCHAR2(100), 
	"WRITER" VARCHAR2(100), 
	"DATEWRITE" DATE, 
	"RECOMMEND" NUMBER(38,0), 
	"VIEWCOUNT" NUMBER(38,0)
   )

   
   
   CREATE TABLE RECOMMEND (
   RE_NO NUMBER(38,0),
   TITLE VARCHAR2(100),
   CONTENT VARCHAR2(100),
   WRITER VARCHAR2(100)
   
   )

   DROP TABLE RECOMMEND  -- 테이블 통째로 던져버림
   
   CREATE TABLE RECOMMEND (
   RE_NO NUMBER(38,0),
   TITLE VARCHAR2(100),
   CONTENT VARCHAR2(100),
   WRITER VARCHAR2(100)
   
   )
   
ALTER TABLE HR.RECOMMEND MODIFY TITLE VARCHAR2(300)
  
ALTER TABLE HR.RECOMMEND MODIFY CONTENT VARCHAR2(300)

ALTER TABLE HR.RECOMMEND ADD VIEWCOUNT NUMBER(38,0) NULL;



 --  D C L : DB관리/제어해주는 문법(계정권한무여, 백업, 복구)

CREATE  USER apple IDENTIFIED BY a1234

GRANT CONNECT, RESOURCE, DBA TO apple

CREATE USER SCOTT
IDENTIFIED BY TIGER;

GRANT CONNECT, RESOURCE, DBA TO SCOTT;




INSERT INTO MEMBER VALUES ('100','100','park','011')

INSERT INTO MEMBER VALUES ('200','200','park','011')

INSERT INTO MEMBER VALUES ('300','300','park','011')

SELECT * FROM MEMBER

SELECT * FROM MEMBER WHERE id = '100' --id가 100인 모든 컬럼


SELECT id FROM MEMBER WHERE id = '100' --id가 100인 id 컬럼

SELECT id, name FROM MEMBER WHERE id = '100' --id가 100인 id,name 컬럼

SELECT name, id FROM MEMBER WHERE id = '100' --id가 100인 id,name 컬럼

SELECT id as 아이디, name FROM MEMBER WHERE id = '100' --id가 100인 id,name 컬럼

SELECT tel FROM MEMBER WHERE name = 'park'

UPDATE MEMBER SET name = 'kim' WHERE id = '100'

UPDATE MEMBER SET name = 'yang' WHERE id = '200'

UPDATE MEMBER SET name = 'lee' WHERE id = '300'
   
SELECT * FROM MEMBER   

UPDATE MEMBER SET pw = '8888', tel = '9999' WHERE id = 'ice'

DELETE FROM MEMBER WHERE ID = '100'

DELETE FROM MEMBER WHERE TEL = '011'

SELECT * FROM MEMBER WHERE ID = '200' AND TEL = '011'

SELECT * FROM MEMBER WHERE ID = '200' OR TEL = '011'

SELECT * FROM MEMBER ORDER BY ID -- (ID기준)오름차순

SELECT * FROM MEMBER ORDER BY id DESC -- (ID기준)내림차순




   