SELECT * FROM PRODUCT 

SELECT * FROM PRODUCT ORDER BY PRICE DESC 

--PRICE가 문자로 되어있기때문에 내림차순 하면 987..순서로 됨
 
SELECT NAME, CONTENT, PRICE FROM PRODUCT ORDER BY COMPANY

SELECT NAME, PRICE FROM PRODUCT WHERE ID = '100'

SELECT NAME, COMPANY FROM PRODUCT WHERE PRICE = '5000'

SELECT NAME, IMG FROM PRODUCT WHERE ID = '100' AND PRICE = '1000'

SELECT COMPANY, NAME FROM PRODUCT WHERE COMPANY = 'c100'

SELECT NAME, PRICE FROM PRODUCT WHERE COMPANY = 'c100' OR COMPANY = 'c200'

UPDATE PRODUCT SET CONTENT = '품절' WHERE PRICE = '5000'

SELECT * FROM PRODUCT WHERE PRICE = '5000'

UPDATE PRODUCT SET IMG = '0.PNG', PRICE = '10000' WHERE ID = '100' OR ID = '102'

SELECT * FROM PRODUCT WHERE ID = '100' OR ID = '102'

UPDATE PRODUCT SET COMPANY = 'apple', NAME = 'appleshoes' WHERE ID = '101'

SELECT * FROM PRODUCT WHERE ID = '101'

DELETE FROM PRODUCT WHERE NAME = 'food1' OR ID = '107'

SELECT * FROM PRODUCT

DELETE FROM PRODUCT WHERE COMPANY = 'c100'

SELECT * FROM PRODUCT

DELETE FROM PRODUCT -- 데이터만 삭제(테이블은 남아있음)

SELECT * FROM PRODUCT

DROP TABLE PRODUCT -- 테이블 까지 전부 삭제



