CREATE TABLE DEPT(
DEPTNO NUMBER(2),
DNAME VARCHAR2(14 BYTE),
LOC VARCHAR2(13 BYTE)
)

ALTER TABLE DEPT ADD (
CONSTRAINT PK_DEPT PRIMARY KEY(DEPTNO));


CREATE TABLE EMP(
EMPNO NUMBER(4),
ENAME VARCHAR2(10 BYTE),
JOB VARCHAR2(9 BYTE),
MGR NUMBER(4),
HIREDATE DATE,
SAL NUMBER(7,2),
COMM NUMBER(7,2),
DEPTNO NUMBER(2)
)

ALTER TABLE EMP ADD (
CONSTRAINT PK_EMP PRIMARY KEY(EMPNO));


CREATE TABLE SALGRADE(
GRADE NUMBER,
LOSAL NUMBER,
HISAL NUMBER
)

ALTER TABLE EMP ADD (
CONSTRAINT FK_DEPTNO FOREIGN KEY (DEPTNO) REFERENCES DEPT (DEPTNO));


SELECT * FROM EMP  --SELECTION

SELECT DEPTNO FROM EMP  -- PROJECTION

SELECT DISTINCT DEPTNO FROM EMP -- DISTINCT

SELECT ENAME, SAL * 12 AS YEARSAL FROM EMP

SELECT * FROM EMP
ORDER BY SAL DESC 

SELECT * FROM EMP
WHERE DEPTNO = 30
ORDER BY EMPNO DESC 

SELECT * FROM EMP
WHERE NOT DEPTNO = 30
ORDER BY EMPNO DESC 

SELECT *FROM EMP 
WHERE DEPTNO = 30 OR JOB = 'SALESMAN'

SELECT *FROM EMP 
WHERE SAL >= 3000

SELECT *FROM EMP 
WHERE SAL != 3000

SELECT *FROM EMP 
WHERE JOB IN ('SALESMAN', 'MANAGER')
ORDER BY JOB

SELECT *FROM EMP 
WHERE JOB NOT IN ('SALESMAN', 'MANAGER')
ORDER BY JOB

SELECT * FROM EMP 
WHERE SAL BETWEEN 1000 AND 3000

SELECT * FROM EMP 
WHERE SAL NOT BETWEEN 1000 AND 3000

SELECT * FROM EMP 
WHERE ENAME LIKE '_L%'

SELECT * FROM EMP 
WHERE ENAME NOT LIKE '_L%'

SELECT * FROM EMP 
WHERE COMM IS NULL 

SELECT * FROM EMP 
WHERE COMM IS NOT NULL 



CREATE TABLE DEPT_TEMP2
AS
SELECT * FROM DEPT

SELECT * FROM DEPT_TEMP2

UPDATE DEPT_TEMP2
SET LOC = 'SEOUL'

UPDATE DEPT_TEMP2
SET DNAME = 'DATABASE', LOC = 'BUSAN'
WHERE DEPTNO = 40

DELETE FROM DEPT_TEMP2
WHERE DNAME = 'SALES'

SELECT * FROM DEPT_TEMP2 DT



