SELECT LENGTH(ENAME) FROM EMP

SELECT LENGTH(ENAME) FROM EMP 
WHERE JOB = 'MANAGER'

SELECT * FROM EMP

SELECT ENAME, JOB FROM EMP
WHERE COMM IS NULL

SELECT HIREDATE FROM EMP 
WHERE COMM IS NOT NULL

SELECT SUBSTR(ENAME,2) FROM EMP

SELECT SUBSTR(ENAME,1,3) FROM EMP

SELECT REPLACE(ENAME, 'K','P') FROM EMP

SELECT EMPNO || '번은 ' || ENAME || '입니다' FROM EMP

SELECT HIREDATE, TO_CHAR(SYSDATE, 'MM') AS MM, 
TO_CHAR(SYSDATE, 'DAY') AS DAY FROM EMP

SELECT JOB, CASE JOB
WHEN 'MANAGER' THEN 'LEVEL1'
WHEN 'SALESMAN' THEN 'LEVEL2'
ELSE 'LEVEL3'
END AS LEVEL_RESULT FROM EMP



----------------------------------------------------


SELECT COUNT(*) FROM EMP

SELECT COUNT(SAL) FROM EMP

SELECT COUNT(SAL), SUM(SAL), AVG(SAL), MIN(SAL), MAX(SAL) FROM EMP 
WHERE JOB = 'SALESMAN'

--ROUND : 정수만 나오게

SELECT JOB, COUNT(SAL), SUM(SAL), ROUND(AVG(SAL)), MIN(SAL), MAX(SAL) 
FROM EMP 
GROUP BY JOB


SELECT JOB, COUNT(SAL), SUM(SAL), ROUND(AVG(SAL)), MIN(SAL), MAX(SAL) 
FROM EMP 
GROUP BY JOB
ORDER BY JOB DESC

SELECT JOB, COUNT(SAL), SUM(SAL), ROUND(AVG(SAL)), MIN(SAL), MAX(SAL) 
FROM EMP 
GROUP BY JOB
HAVING COUNT(SAL) >=4   ---그룹 지어서 검색 후, 필터링(조건) 하고자 하는 경우
ORDER BY JOB DESC  --이미 모든 검색이 다 끝난 후, 그 결과를 정렬하고자 하는 경우, 맨 끝에 작성


----------------------------------------------------------------

SELECT COUNT(*) FROM EMP

SELECT COUNT(*) FROM EMP 
WHERE DEPTNO = 20 OR MGR <=7700

SELECT MIN(SAL) FROM EMP 
WHERE DEPTNO = 10 OR DEPTNO = 20

SELECT MIN(SAL), MAX(SAL), SUM(SAL) FROM EMP

SELECT DEPTNO, AVG(SAL) FROM EMP
GROUP BY DEPTNO

SELECT DEPTNO, SUM(SAL) FROM EMP
GROUP BY DEPTNO
ORDER BY DEPTNO

SELECT DEPTNO, AVG(SAL) FROM EMP
GROUP BY DEPTNO 
HAVING AVG(SAL) >= 2000
ORDER BY DEPTNO DESC

SELECT COUNT(*), AVG(SAL) FROM EMP 
WHERE JOB = 'MANAGER'

SELECT COUNT(*) FROM EMP
WHERE ENAME LIKE '%S%'

SELECT COUNT(*) FROM EMP
WHERE SAL >=3000 AND COMM IS NOT NULL 
ORDER BY SAL DESC

















