CREATE TABLE "HR"."MEMBER" 
   (	
   	"ID" VARCHAR2(10), 
	"PW" VARCHAR2(10), 
	"NAME" VARCHAR2(10), 
	"TEL" VARCHAR2(10)
   ) 
   
   
   CREATE TABLE "HR"."BBS"
(	
	"no" VARCHAR2(100),
	"TITLE" VARCHAR2(100),
	"CONTENT" VARCHAR2(100),
	"WRITER" VARCHAR2(100)
)
   
   
   
   
   CREATE TABLE PRODUCT(
ID VARCHAR2(200),
NAME VARCHAR2(200),
CONTENT VARCHAR2(200),
PRICE VARCHAR2(200),
COMPANY VARCHAR2(200),
IMG VARCHAR2(200)
)

-- 저장할 대상 : 엔티티(회원정보, 게시판, 상품), 엔티티간의 관계 : 회원이 상품을 주문하다(주문정보)
--            엔티티 + 관계 ==> 테이블로 만들자!!


CREATE TABLE orderlist (
	"no" VARCHAR2(100),
	member_id varchar2(100),
	product_id varchar2(100),
	total_count varchar2(100)
)


CREATE TABLE "HR"."BBS22" 
(	"no" VARCHAR2(100), 
	"TITLE" VARCHAR2(100), 
	"CONTENT" VARCHAR2(100), 
	"WRITER" VARCHAR2(100), 
	 CONSTRAINT "BBS_PK22" PRIMARY KEY ("no"),
	 CONSTRAINT "FK_MEMBER22" FOREIGN KEY ("WRITER")
	  REFERENCES "HR"."MEMBER" ("ID")
) 


CREATE TABLE "HR"."BBS3" 
(	"no" VARCHAR2(100), 
	"TITLE" VARCHAR2(100), 
	"CONTENT" VARCHAR2(100), 
	"WRITER" VARCHAR2(100)
)

--PK제약조건 추가

ALTER TABLE HR.BBS3
ADD CONSTRAINT BBS3_PK PRIMARY KEY ("no")


--FK제약조건 추가

ALTER TABLE HR.BBS3
ADD CONSTRAINT FK_MEMBER33 
FOREIGN KEY (WRITER) REFERENCES HR."MEMBER"(ID);



CREATE TABLE "HR"."DEPART2" 
   (	"ID" VARCHAR2(100), 
	"NAME" VARCHAR2(100), 
	"INSTRUCTOR" VARCHAR2(100), 
	 CONSTRAINT "DEPART2_PK" PRIMARY KEY ("ID")
	 )
	 
	 
CREATE TABLE "HR"."STUDENT2" 
   (	"ID" VARCHAR2(100), 
	"NAME" VARCHAR2(100) NOT NULL ENABLE, 
	"TEL" VARCHAR2(100), 
	"DEPART_ID" VARCHAR2(100)
	)

ALTER TABLE HR.STUDENT2
ADD CONSTRAINT STUDENT2_PK PRIMARY KEY ("ID")



ALTER TABLE HR.STUDENT2
ADD CONSTRAINT FK_STUDENT2 
FOREIGN KEY (DEPART_ID) REFERENCES HR."DEPART2"(ID);


-- 테이블 복사

CREATE TABLE MEMBER22
AS SELECT * FROM MEMBER

INSERT INTO MEMBER22 
VALUES ('BANANA3','BANANA3','BANANA3','BANANA3',SYSDATE)

SELECT * FROM MEMBER22

INSERT INTO MEMBER22 
VALUES ('BANANA4','BANANA4','BANANA4','BANANA4',SYSDATE,'AAA')

INSERT INTO BBS 
VALUES (BBS_ID_SEQ.NEXTVAL, 'HAPPY', 'HAPPY DAY' , 'ICE')

INSERT INTO BBS 
VALUES (BBS_ID_SEQ.NEXTVAL, 'HAPPY2', 'HAPPY DAY2' , 'ICE')

SELECT * FROM BBS

CREATE SEQUENCE PRO_ID_SEQ 
INCREMENT BY 1 START WITH 1  

CREATE TABLE PRODUCT2 (
	ID NUMBER(38, 0),
	NAME VARCHAR2(100)
)

INSERT INTO PRODUCT2
VALUES (PRO_ID_SEQ.NEXTVAL, 'APPLE')

SELECT * FROM PRODUCT2 



CREATE SEQUENCE OR_SEQ
INCREMENT BY 1 START WITH 1

CREATE TABLE ORDERLIST3 (
	ID NUMBER(38,0),
	TITLE VARCHAR2(100),
	PRICE NUMBER(38,0)
)
	
INSERT INTO ORDERLIST3
VALUES (OR_SEQ.NEXTVAL, 'AAA',1000)

SELECT * FROM ORDERLIST3 

SELECT * FROM ORDERLIST3 
ORDER BY ID  -- 오름차순

SELECT * FROM ORDERLIST3 
WHERE ID >= 3
ORDER BY ID DESC -- 내림차순



	


